### ISSUE TITLE
Config Tragedy

### ISSUE THREAD

**Issue by ainsleymcgrath** [ainsleymcgrath/nothing#27]
So, as it happens, early design decisions in `nothing_cli.config` did not pan out. `$HOME/.nothing._config.yaml` does not take hold in any of the places where it should 😬 

Since the tool began mostly as an excuse to play around with Pydantic , i hoped to make use of their [settings management features](https://pydantic-docs.helpmanual.io/usage/settings/). 

Unfortunately, the use of a file (as opposed to environment variables) isn't compatible in a straightforward way with that approach. I'm trapped with yaml since some settings are complex data types such as lists and block scalars. Plus, the whole project is a love letter to yaml, and I don't want to give it up.

**DOD** the `Config` and `GlobalConfig` classes are replaced with custom classes that can read from and write to `$HOME/.nothing/_config.yaml`.

**Comment by ainsleymcgrath** [comment]
Chatting with @SalomonSmeke today, we came to the conclusion that "high config" is no longer a value of this application. Most of the options provided were odd tertiary redundancies or just straight up useless.

**Comment by SalomonSmeke** [comment]
I have mouth and with it I speak.
