### ISSUE TITLE
"Task Spec" might be a bad name

### ISSUE THREAD

**Issue by ainsleymcgrath** [ainsleymcgrath/nothing#4]
A global renaming ticket, pending agreement on a better name.

Candidates:
1. Recipe
2. Routine
3. Protocol
4. Operation
5. Guide
6. ???

**Comment by zachgarwood** [comment]
Maybe "dialogue" might be better, to get away from the programmer connotation of "script"?

**Comment by ainsleymcgrath** [comment]
After much re-reading of the [original post](https://blog.danslimmon.com/2019/07/15/do-nothing-scripting-the-key-to-gradual-automation/) and quietly ruminating, I'm now between _Procedure_ and _Manual_.

Dan Slimmon uses both words in the first sentence of his post:
> Every ops team has some **manual procedures** that they haven’t gotten around to automating yet. Toil can never be totally eliminated.

I like _Procedure_ because it feels incredibly obvious. "Can you send me that Procedure?" It shortens nicely to `proc`, doing away with the millions of character-heavy `task_spec_*` names floating around...

_Manual_ reminds me of working in a lab and following along with the _Lab Manual_ all day long to complete toilsome tasks accurately. `man` is a pretty friendly shortening as well. That said I don't necessarily think that idea of a "manual" being a set of instructions for a task jives with the idiomatic meaning of the word "manual" for your average programmer...
