### ISSUE TITLE
Do we need our own extension?

### ISSUE THREAD

**Issue by ainsleymcgrath** [ainsleymcgrath/nothing#7]
It was a cute idea, but why even make it optional to create a `[wd]/.nothing` directory?

_"There should be one-- and preferably only one --obvious way to do it."_

The redundancy has already caused some cognitive & technical hiccups i.e.
- Editor support. Nobody's editor knows what a `.not` is.
- Defaults. If the default extension is `.not`, then logically the default directory for new spec creation is `.`. But what about when the user interactively decides they'd rather use `.yml`? In order for the spec to be located, it would need to go in `~/.nothing` or `./.nothing`, since `filesystem.task_spec_location` does not search for any extension other than `.not` in cwd... Even in prose, the logic becomes acrobatic.

Consider the benefits and drawbacks. 
Maybe some people hate amassing random hidden directories?

**Comment by zachgarwood** [comment]
I think a file extension should describe the contents of the file, not the application the file is used for.
